---
apiVersion: v1
kind: Secret
metadata:
  name: {{ required "nbprimaryserver value is required" .Values.netbackupkops.containers.manager.nbprimaryserver }}
  namespace: {{ .Release.Namespace }}
stringData:
  caCert: {{ required "nbcert value is required" .Values.netbackupkops.containers.manager.nbcert | quote }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: datamover-secret-{{ required "nbprimaryserver value is required" .Values.netbackupkops.containers.manager.nbprimaryserver }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  token: {{ required "securityToken value is required" .Values.netbackupkops.containers.manager.securityToken }}
  fingerprint: {{ required "sha256Fingerprint value is required" .Values.netbackupkops.containers.manager.sha256Fingerprint }}
